### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by paul-seal** [umco/umbraco-fluidity#12]
When trying to use the documentation, I found 3 things which didn't work from a copy and paste perspective. I assume the code has changed slightly.

It needed a description parameter value in `AddCollection`, but the example in the docs doesn't have a description

`treeConfig.AddCollection<Person>(p => p.Id, "Person", "People", "THIS WAS MISSING", "icon-umb-users", "icon-umb-users", collectionConfig => {`

The `.IsRequired()` method on `AddField()` doesn't work any more I had to change it to `.MakeRequired()`

The email regex was saying any of my email addresses weren't valid. This is the one used in the docs:
`[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}`

So I changed it to use the one which Umbraco gives you as an example and it works fine now.
`[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+`

**Comment by mattbrailsford** [comment]
If you are up for contributing this would make a great starter pull request? All the docs are in the docs folder.

No worries if not, I'll get to it when I can.

**Comment by paul-seal** [comment]
Yes I'm happy to do it mate. No problem

**Comment by mattbrailsford** [comment]
Fixed by PR #13 

Cheers Paul
