### ISSUE TITLE
Advantage over Content Nodes?

### ISSUE THREAD

**Issue by coonmoo** [umco/umbraco-fluidity#15]
First of all, thank you very much for this package.
It works like a charm!

But I'm not sure what kind of advantage does this project offer compared to "normal" Umbraco content nodes where creating the same structures is possible?

**Comment by mattbrailsford** [comment]
Hey Coonmo

That's a really good question.

Generally speaking, content nodes in umbraco or just that, content. With
this comes a bunch of "content" based features such as routing, publishing
and unpublished, versioning and audit trails to name a few.

Now these might all sound handy, but when dealing with lots of data, these
can all add up to cause some big performance issues. There are packages
such as UnVersion which can help with limiting the versions history, but if
you don't want the other features and their overheads, there isn't really
any way to turn them off.

Another issue with using content nodes is that the data will all now be in
our internal and external lucene indexes, which at best may require you to
write code to exclude it or at worst, if left, could balloon your index
sizes and slow your index builds.

Next up is the content dB structure. This is completely outside of your
control so becomes considerably harder for you to access the data outside
of the cms context. And again, the structure may not be optimal for your
needs.

Lastly, if you already have a database table, or other external data store
with data in it that you need to manage, then using the content section
isnt going to work at all.

Generally speaking then, these are the main reasons why it's considered bad
practice to use the content structure for storing "data".

Fluidity then is built to allow you to create/use efficient data stores
whilst keeping a level of ui consistency and making it simple to build a
custom management interface.

With fluidity, we provide just the ui you need for your data (reusing
things like property editors), and leave the rest to you, as who knows your
data needs better than you.

Hope this helps explain the differences and when/why you should use each
approach.

Matt

**Comment by coonmoo** [comment]
Thanks alot for the explanation. Makes perfectly sense!
