### ISSUE TITLE
Enable MakeReadonly() on all or most datatypes

### ISSUE THREAD

**Issue by kasperskov909** [umco/umbraco-fluidity#21]
Feature suggestion.
MakeReadonly() method on a field rendeers a label. Wouldn't it be cool if it just rendered the assigned data type/editor instead in disabled mode?

Example. Say we have an interger property that works as an Umbraco User reference. No fun in reading a number. Reading the `User.Name` is way more informative in most cases.

**Comment by mattbrailsford** [comment]
Umbraco property editors don't support a "disabled" mode so anything we did to make that happen would be a hack, so wouldn't be interested in adding that.

The best I could suggest though would be to maybe provide a format function for any field you want to be readonly, then you could do some logic to get a meaningul value.

**Comment by kasperskov909** [comment]
Alright fair enough. I think I'll implement FluidityValueMapper. It just seemed a bit overkill considering all editors are supported.
