### ISSUE TITLE
Workaround or even a feature for sorting on DataTime datatype

### ISSUE THREAD

**Issue by kasperskov909** [umco/umbraco-fluidity#22]
Hi Matt
Are you familiar with a hack or workaround for DateTime sorting in the list?
Date sorting is very common imo, so even a fix/new feature would be awesome.

I was hoping that formatting the DateTime to a String with `SetFormat()` on the list field would do the trick - unfortunately not.

**Comment by mattbrailsford** [comment]
Can you explain what you are seeing? I've created some test models with dates on and in the listview it appears I can sort by them clicking the heading in the list view for that content.

**Comment by mattbrailsford** [comment]
Closing as seems to work ok for me. Feel free to reopen if you have more info.
