### ISSUE TITLE
Custom filters or DataViews to support more than just boolean expressions.

### ISSUE THREAD

**Issue by kasperskov909** [umco/umbraco-fluidity#23]
Hi Matt
The state of an entity isn't always determinated with a boolen but rather with a DateTime or maybe even a status code in the form of an interger.
Imagine if you could make custom filters/DataViews on the list with ie. string or DateTime comparison. That would make this product perfect!
I'm not sure what would be the best approach but I fancy the possibility of simply doing:
`listViewConfig.AddDataView("Ended", p => (p.End > DateTime.Now ));`

What's your thoughts?

**Comment by mattbrailsford** [comment]
At this point, I think we are just at the whim of the built-in Umbraco linq to sql implementation. Any improvements to this would need to be made to the core as I'm not looking to implement a custom implementation. The only workaround I can think of at the moment would be to create a custom repository and implement the logic yourself. Unfortunately, my linq to sql knowledge isn't that good.

Closing the issue for now, but will see keep an eye on the demand.

**Comment by mattbrailsford** [comment]
Hmm, I thought I'd take a quick look at this and I have added a datetime property to my model, setting some db entries with a date in the past and some in the future, then had a list view config like so:

````
listViewConfig.AddDataView("Ended", person => person.End <= DateTime.Now);
listViewConfig.AddDataView("Open", person => person.End > DateTime.Now);
````
And this worked as expected. I had a dropdown for the dataview and could toggle betwee ended and open.
