### ISSUE TITLE
Fluidity doesn't set hideLabel 

### ISSUE THREAD

**Issue by skartknet** [umco/umbraco-fluidity#32]
If I turn on the Hide Label property of a stacked content, label is still displayed. I found that `FluidityentityMapper.ToEditModel:152` uses `dataTypeInfo.PropertyEditor.ValueEditor.ConfigureForDisplay(dataTypeInfo.PreValues);` to set up the editor values but it looks like thast method doesn't set up the HideLabel property.

I found a method with the same name on the NestedContentPropertyEditor that is used for that. Maybe it was intended to use that one?

**Comment by mattbrailsford** [comment]
Thanks for the info. This looks like more of an issue with stacked content than fluidity so I've raised an issue on the stacked content repository to address this https://github.com/umco/umbraco-stacked-content/issues/37

Closing this issue.
