### ISSUE TITLE
Could use an external database?

### ISSUE THREAD

**Issue by biapar** [umco/umbraco-fluidity#34]
Could use an external database?

**Comment by mattbrailsford** [comment]
You sure can. If you are still using peta poco you can just change a collections connection string

https://umco.github.io/umbraco-fluidity/api/collections/#changing-a-collection-connection-string

If you are wanting to use a completely custom database strategy though you'll need to looks at creating a custom repository

https://umco.github.io/umbraco-fluidity/api/repositories/

**Comment by biapar** [comment]
I wish to use RethinkDB.

**Comment by mattbrailsford** [comment]
In that case then yea, you'd need to look at implementing your own repository as per the docs here https://umco.github.io/umbraco-fluidity/api/repositories/ As long as you implement the methods used by Fluidity then it will just work :)
