### ISSUE TITLE
Tiny spelling mistake FluidityCollectionConfig

### ISSUE THREAD

**Issue by james-whittington1** [umco/umbraco-fluidity#38]
Fluidity.Configuration.FluidityCollectionConfig.connectionStringg has an extra g on the end, which is at odds with the documentation.

**Comment by mattbrailsford** [comment]
Hi James,

I've gone ahead and fixed that so thanks for raising it.

Just to check, are you actually using that property? The one with the spelling mistake was an internal property that shouldn't be used, instead, the `SetConnectionString(string connStrName)` should be used publicly which is [consistent with the documentation](https://umco.github.io/umbraco-fluidity/api/collections/#changing-a-collection-connection-string).

**Comment by james-whittington1** [comment]
I'm not using it, I just noticed it while investigating how to implement my own repository with a custom database string.  Cheers
