### ISSUE TITLE
Add support to configure sorting options for mini list view

### ISSUE THREAD

**Issue by netaddicts** [umco/umbraco-fluidity#46]
Hi Matt,

Any chance we could have the same sorting options for mini listview (in picker) as we have for standard default list views?

orderBy: $scope.opts.defaultOrderBy || "name",
orderDirection: $scope.opts.defaultOrderDirection || "desc",

instead of the hard coded

orderBy: "name",
orderDirection: "desc",

It makes sense to have the same sorting options when using the picker to select a Fluidity entity as when using the standard list view, right?

**Comment by netaddicts** [comment]
If i knew where to start, i could yes... didn't have a look at the code, just helping out a co-working who doesn't have a GitHub account (Can you image!?)

**Comment by netaddicts** [comment]
I'll start by forking the repo 😆

**Comment by mattbrailsford** [comment]
Hehe, no worries. I can take a look when I have a mo.
