### ISSUE TITLE
Record Security

### ISSUE THREAD

**Issue by mrafea-sa** [umco/umbraco-fluidity#47]
In multi user environment,it is needed to know how added this record , how updated this record (the last operation of update).
i suggest add new DataAnnotations fields for CreatedBy ,UpdatedBy,CreatedOn,UpdatedON.

**Comment by mattbrailsford** [comment]
Fluidity already supports timestamp properties which you can find docs on
here

https://umco.github.io/umbraco-fluidity/api/collections/#defining-time-stamp-properties

We don't yet have support for who created / edited though so we will need
to think about that.

Thanks for the suggestion

Matt
