### ISSUE TITLE
Add in MakeAllReadonly() function for EditorConfig

### ISSUE THREAD

**Issue by jamiepollock** [umco/umbraco-fluidity#53]
Hello!
Loving the work ``MakeReadonly()`` on ``FieldConfig``s would a potential top level function for EditorConfig called ``MakeAllReadonly()`` fit in the project?

This would be a time saver for having to set each field as ``MakeReadonly()``.

I'm happy to look into a PR if you're happy with the expected functionality.

I'm expecting this to be a "default" and if a developer really wants to they can override it on a per field basis.

Thanks,
Jamie

**Comment by mattbrailsford** [comment]
It shouldn't be necessary. I've recently added (not yet released) that
setting a collection read only, auto makes editor fields readonly unless a
data type is explicitly set on a field.

**Comment by jamiepollock** [comment]
Ah well then I'm looking forward to that release! I noticed it wasn't current behaviour in the live version. :)

I'm happy to close this issue now I know it's coming up in a future release

Thanks Matt! #h5yr!.
