### ISSUE TITLE
Remote repository

### ISSUE THREAD

**Issue by clarkd** [umco/umbraco-fluidity#54]
We're looking at using this for a project in which the data is stored in an external database (3rd party) to which we have API access. Could we implement a custom FluidityRepository that makes API calls to retrieve the data?

Do you have any examples or experience with this kind of scenario?

**Comment by mattbrailsford** [comment]
You absolutely can do this yes, and you are right that you would need to create a custom FluidityRepository. The docs for this are here which outline the methods you'd need to implement:

https://umco.github.io/umbraco-fluidity/api/repositories/

I don't have any specific examples myself at the moment, but hopefully, the simplicity of the repository interface is self explanatory. As long as you implement those methods, then it should "just work".

**Comment by clarkd** [comment]
Awesome - and thanks for the quick reply! I'll let you know how I get on.
